### ISSUE TITLE
Update to React 18

### ISSUE THREAD

**Issue by TheodorTomas** [pelcro-inc/react-pelcro-js#240]
There is a warning coming from this library when using `usePelcro()` when using this package with React 18. Could you please update to the latest version of React?

The following error is:

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

**Comment by Shaker-Pelcro** [comment]
Hello @TheodorTomas.
I'm sorry for not getting back to you sooner. We will look into upgrading our dev and peer dependencies in the near future.
